= ihet.dev
This repository holds the resources for my personal developer website.

You can visit my website at link:https://www.ihet.dev[https://www.ihet.dev].

== Resources

This website was build on top of the link:https://startbootstrap.com/theme/freelancer[Startbootstrap Freelancer] template.

This website uses icons available at link:https://icon-icons.com[https://icon-icons.com].

Additionally this website uses images of technologies I work with which have been downloaded from their corrspoding website which linked with the images.

== Privacy

TODO: Document how integrated and managed

=== Google Analytics

TODO: Document how integrated and used

== AWS CDK 

This website is deployed on AWS Amplify, and the infrastructure is definied via the AWS CDK Java.

See link:aws/src/main/java/dev/ihet/aws/amplify/AwsStack.java[AwsStack.java] for the infrastructure definition.

The AWS Stack relies on an external `configuration.json` file which has to be located in the directory `aws`, and which provides the configuration for the infrastructure.

.configuration.json
[source,json]
----
{
    "name": "AMPLIFY_APPLICATION_NAME",
    "account": "AWS_ACCOUNT_ID",
    "region": "AWS_REGION",
    "repository": "URL_TO_THE_REPOSITORY",
    "branchName": "THE_BRANCH_FOR_WWW_AND_NOTIFICATIONS",
    "accessToken": "GH_ACCESS_TOKEN_FOR_AMPLIFY",
    "domain": "DOMAIN"
}
----

IMPORTANT: The `name` propery is also used to create the aws-stack and resource-ids. 
           Don't change the name before you have deleted the aws-stack, otherwise the stack cannot be deleted anymore. 

WARNING: If you re-create the AWS Amplify application, then cleanup your old DNS entries pointing to the old application.
         Otherwise the sub-domain creation will fail because of that. The domain has to been already verified by AWS as well.

