= ihet.dev
This repository holds the resources for my personal developer website.

You can visit my website at link:https://www.ihet.dev[https://www.ihet.dev].

== Resources

This website was build on top of the link:https://startbootstrap.com/theme/freelancer[Startbootstrap Freelancer] template.

This website uses icons available at link:https://icon-icons.com[https://icon-icons.com].

Additionally this website uses images of technologies I work with which have been downloaded from their corrspoding website which linked with the images.

== Privacy

TODO: Document how integrated and managed

=== Google Analytics

TODO: Document how integrated and used

== AWS CDK 

This website is deployed on AWS Amplify, and the infrastructure is definied via the AWS CDK Java.

See link:aws/[AWS CDK Resources] for the infrastructure definition.

=== Preconditions

Some manual steps are required before the infrastructure can be created which are documented here.

* Public certificate managed by `Certificate Manager` +
The pulic certificate used by the backend rest-api where the certificate ARN needs to be configured in the `configuration.json`. The following names need to be part of the certificate:
** `<CONFIGURED_DOMAIN>`
** `api.<CONFIGURED_DOMAIN>` 

* SES verified email +
Add the arn of the verified email to `configuration.json`

.configuration.json
[source,json]
----
{
    "name": "AMPLIFY_APPLICATION_NAME",
    "account": "AWS_ACCOUNT_ID",
    "region": "AWS_REGION",
    "repository": "URL_TO_THE_REPOSITORY",
    "branchName": "THE_BRANCH_FOR_WWW_AND_NOTIFICATIONS",
    "accessToken": "GH_ACCESS_TOKEN_FOR_AMPLIFY",
    "domain": "DOMAIN",
    "apiKey": "THE_API_KEY_FOR_THE_BACKEND",
    /* optional, if note present, then no google analytics is enabled and no consent is required */
    "gId": "THE_GOOGLE_ANALYTICS_ID",
    "sesArn": "THE_ARN_OF_THE_VERIFIED_EMAIL"
}
----

IMPORTANT: The `name` propery is also used to create the aws-stack and resource-ids. 
           Don't change the name before you have deleted the aws-stack, otherwise the stack cannot be deleted anymore. 

WARNING: If you re-create the AWS Amplify application, then cleanup your old DNS entries `CNAME=www` pointing to the old application.
         Otherwise the sub-domain creation will fail because of that. The domain has to been already verified by AWS as well.

